const whatsappNumber='5585994211235';
const serviceInfo={miofascial:{title:'Liberação miofascial',text:'Cuidado muscular voltado às regiões exigidas na sua atividade física. A avaliação orienta a escolha dos recursos para cada atendimento.',items:['Avaliação postural','Liberação miofascial manual','Fotobiomodulação','Eletroestimulação','Agulhamento a seco','Termoterapia','Ventosaterapia']},drenagem:{title:'Drenagem linfática',text:'Técnicas manuais suaves e recursos de cuidado corporal para complementar sua rotina, conforme suas necessidades e avaliação.',items:['Drenagem linfática manual','Botas pneumáticas','Termoterapia']},recovery:{title:'Recovery para você',text:'Um momento de cuidado entre os treinos, com atenção às demandas da sua rotina esportiva e aos seus limites.',items:['Liberação miofascial de membros superiores','Botas pneumáticas','Crioterapia (piscina de gelo)']}};
const modal=document.querySelector('#service-modal');
document.querySelectorAll('[data-service]').forEach(card=>card.addEventListener('click',()=>{const d=serviceInfo[card.dataset.service];document.querySelector('#modal-title').textContent=d.title;document.querySelector('#modal-text').textContent=d.text;document.querySelector('#modal-list').innerHTML=d.items.map(i=>`<li>✦ ${i}</li>`).join('');modal.showModal();}));
document.querySelector('.modal-close').onclick=()=>modal.close();
document.querySelector('.modal-cta').addEventListener('click',()=>modal.close());
document.querySelector('.menu').addEventListener('click',()=>document.querySelector('nav').classList.toggle('open'));
document.querySelector('#booking-form').addEventListener('submit',e=>{e.preventDefault();const name=document.querySelector('#client-name').value.trim();const service=document.querySelector('#client-service').value;const message=`Olá, David! Meu nome é ${name} e tenho interesse em ${service}.`;window.open(`https://wa.me/${whatsappNumber}?text=${encodeURIComponent(message)}`,'_blank','noopener');});
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('reveal')}),{threshold:.12});document.querySelectorAll('.section,.intro-strip,.quote-section').forEach(e=>observer.observe(e));
